language: python

python:
  - "2.7"
  - "3.4"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0d0a3e649189d346b6f6
    on_success: change
    on_failure: always
    on_start: false

before_install:
  - "curl -X POST http://readthedocs.org/build/pytodoist"

install:
  - "pip install flake8 --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"

script: make test
